create extension if not exists "uuid-ossp";

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'operator',
  full_name text not null,
  employee_id text,
  mobile text,
  status text not null default 'active',
  created_at timestamptz default now()
);

create table if not exists intersections (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  latitude double precision,
  longitude double precision,
  radius_meters int default 100,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists shifts (
  id bigint generated by default as identity primary key,
  name text not null,
  start_time text not null,
  end_time text not null,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  operator_id uuid not null references profiles(id) on delete cascade,
  intersection_id bigint references intersections(id),
  shift_id bigint references shifts(id),
  shift_in_at timestamptz,
  shift_out_at timestamptz,
  status text not null default 'on-duty',
  gps_lat_in double precision,
  gps_lng_in double precision,
  gps_accuracy_in double precision,
  gps_lat_out double precision,
  gps_lng_out double precision,
  gps_accuracy_out double precision,
  distance_meters double precision,
  browser text,
  device text,
  os text,
  ip_address text,
  notes text,
  created_at timestamptz default now()
);

alter table profiles enable row level security;
alter table intersections enable row level security;
alter table shifts enable row level security;
alter table attendance enable row level security;

create policy "Profiles self and admin" on profiles
for select using (auth.uid() = id or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "Profiles manage own" on profiles
for insert with check (auth.uid() = id);

create policy "Profiles admin update" on profiles
for update using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "Read intersections" on intersections for select using (auth.role() = 'authenticated');
create policy "Admin manage intersections" on intersections for all using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "Read shifts" on shifts for select using (auth.role() = 'authenticated');
create policy "Admin manage shifts" on shifts for all using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "Attendance self or admin" on attendance for select using (
  auth.uid() = operator_id or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "Attendance insert own" on attendance for insert with check (auth.uid() = operator_id);
create policy "Attendance update own or admin" on attendance for update using (
  auth.uid() = operator_id or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin')
);

insert into intersections (name, code, latitude, longitude, radius_meters, active)
values
  ('North Gate', 'NG1', 23.7549, 90.3760, 120, true),
  ('Airport Road', 'AR2', 23.7630, 90.3890, 140, true),
  ('City Center', 'CC3', 23.7500, 90.3950, 110, true)
on conflict (code) do nothing;

insert into shifts (name, start_time, end_time, active)
values
  ('Shift 1', '06:00', '14:00', true),
  ('Shift 2', '14:00', '22:00', true),
  ('Shift 3', '22:00', '06:00', true)
on conflict do nothing;
