create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

create table if not exists profiles (
  id uuid primary key default uuid_generate_v4(),
  role text not null default 'operator',
  full_name text not null,
  employee_id text,
  mobile text unique,
  password_hash text not null,
  status text not null default 'active',
  created_at timestamptz default now()
);

create table if not exists intersections (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  latitude double precision,
  longitude double precision,
  radius_meters int default 100,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists shifts (
  id bigint generated by default as identity primary key,
  name text not null,
  start_time text not null,
  end_time text not null,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  operator_id uuid not null references profiles(id) on delete cascade,
  intersection_id bigint references intersections(id),
  shift_id bigint references shifts(id),
  shift_in_at timestamptz,
  shift_out_at timestamptz,
  status text not null default 'on-duty',
  gps_lat_in double precision,
  gps_lng_in double precision,
  gps_accuracy_in double precision,
  gps_lat_out double precision,
  gps_lng_out double precision,
  gps_accuracy_out double precision,
  distance_meters double precision,
  browser text,
  device text,
  os text,
  ip_address text,
  notes text,
  created_at timestamptz default now()
);

alter table profiles enable row level security;
alter table intersections enable row level security;
alter table shifts enable row level security;
alter table attendance enable row level security;

drop policy if exists "Profiles self and admin" on public.profiles;
drop policy if exists "Profiles manage own" on public.profiles;
drop policy if exists "Profiles admin update" on public.profiles;

drop policy if exists "Read intersections" on public.intersections;
drop policy if exists "Admin manage intersections" on public.intersections;
drop policy if exists "Read shifts" on public.shifts;
drop policy if exists "Admin manage shifts" on public.shifts;
drop policy if exists "Attendance self or admin" on public.attendance;
drop policy if exists "Attendance insert own" on public.attendance;
drop policy if exists "Attendance update own or admin" on public.attendance;

create or replace function public.register_operator(
  p_full_name text,
  p_employee_id text,
  p_mobile text,
  p_password text,
  p_role text default 'operator',
  p_status text default 'pending'
)
returns table (id uuid, full_name text, employee_id text, mobile text, role text, status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hash text;
  v_id uuid;
begin
  if p_mobile is null or length(trim(p_mobile)) = 0 then
    raise exception 'Mobile number is required';
  end if;

  if p_password is null or length(p_password) < 4 then
    raise exception 'Password must be at least 4 characters';
  end if;

  if exists (select 1 from public.profiles where mobile = trim(p_mobile)) then
    raise exception 'This mobile number is already registered';
  end if;

  v_hash := crypt(p_password, gen_salt('bf'));
  v_id := uuid_generate_v4();

  insert into public.profiles (
    id,
    role,
    full_name,
    employee_id,
    mobile,
    password_hash,
    status
  ) values (
    v_id,
    coalesce(p_role, 'operator'),
    trim(p_full_name),
    trim(p_employee_id),
    trim(p_mobile),
    v_hash,
    coalesce(p_status, 'pending')
  );

  return query
  select p.id, p.full_name, p.employee_id, p.mobile, p.role, p.status
  from public.profiles p
  where p.id = v_id;
end;
$$;

create or replace function public.login_operator(p_phone text, p_password text)
returns table (id uuid, full_name text, employee_id text, mobile text, role text, status text)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  select
    p.id,
    p.full_name,
    p.employee_id,
    p.mobile,
    p.role,
    p.status
  from public.profiles p
  where lower(trim(p.mobile)) = lower(trim(p_phone))
    and p.password_hash = crypt(p_password, p.password_hash);
end;
$$;

create policy "Profiles read public" on public.profiles
for select using (auth.role() = 'anon' or auth.role() = 'authenticated');

create policy "Profiles manage public" on public.profiles
for all using (auth.role() = 'anon' or auth.role() = 'authenticated')
with check (auth.role() = 'anon' or auth.role() = 'authenticated');

create policy "Read intersections" on public.intersections for select using (auth.role() = 'anon' or auth.role() = 'authenticated');
create policy "Admin manage intersections" on public.intersections for all using (auth.role() = 'anon' or auth.role() = 'authenticated')
with check (auth.role() = 'anon' or auth.role() = 'authenticated');

create policy "Read shifts" on public.shifts for select using (auth.role() = 'anon' or auth.role() = 'authenticated');
create policy "Admin manage shifts" on public.shifts for all using (auth.role() = 'anon' or auth.role() = 'authenticated')
with check (auth.role() = 'anon' or auth.role() = 'authenticated');

create policy "Attendance access public" on public.attendance for all using (auth.role() = 'anon' or auth.role() = 'authenticated')
with check (auth.role() = 'anon' or auth.role() = 'authenticated');

insert into intersections (name, code, latitude, longitude, radius_meters, active)
values
  ('North Gate', 'NG1', 23.7549, 90.3760, 120, true),
  ('Airport Road', 'AR2', 23.7630, 90.3890, 140, true),
  ('City Center', 'CC3', 23.7500, 90.3950, 110, true)
on conflict (code) do nothing;

insert into shifts (name, start_time, end_time, active)
values
  ('Shift 1', '06:00', '14:00', true),
  ('Shift 2', '14:00', '22:00', true),
  ('Shift 3', '22:00', '06:00', true)
on conflict do nothing;
